[workspace]
members = [
    "modules/account",
    "modules/app",
    "modules/app_wasm",
    "modules/bluetooth",
    "modules/core",
    "modules/frontbridge",
    "modules/netcfg",
    "modules/pb",
    "modules/pluginsystem",
    "modules/privaccount",
    "modules/privprovider",
    "modules/provider",
    "modules/vivo_msgpack",
    "plugins/android-widgets",
    "plugins/btclassic-spp",
    "plugins/live-activity",
]
exclude = [
    "modules/app_esp32s3",
]
resolver = "3"

default-members = [
    "modules/app",
]

[patch.crates-io]
rustix = { git = "https://github.com/bytecodealliance/rustix", version = "1.1.4" }
swift-rs = { git = "https://github.com/Searchstars/swift-rs", branch = "main" }
wasmtime-internal-fiber = { git = "https://github.com/Searchstars/wasmtime", branch = "astrobox-38.0.4-android-fiber-fix" }
