[workspace]
members = [
    "modules/account",
    "modules/app",
    "modules/app_wasm",
    "modules/bluetooth",
    "modules/core",
    "modules/frontbridge",
    "modules/netcfg",
    "modules/pb",
    "modules/pluginsystem",
    "modules/privaccount",
    "modules/privprovider",
    "modules/provider",
    "modules/vivo_msgpack",
    "plugins/android-widgets",
    "plugins/btclassic-spp",
    "plugins/live-activity",
]
exclude = [
    "modules/app_esp32s3",
]
resolver = "3"

default-members = [
    "modules/app",
]

[patch.crates-io]
rustix = { git = "https://github.com/66hh/rustix-android-patch", branch = "main" }

[profile.fast-release]
inherits = "release"
codegen-units = 64
incremental = true
lto = false
opt-level = 0
debug = true
strip = false

[profile.debug-release]
inherits = "fast-release"
codegen-units = 1
split-debuginfo = "unpacked"
